### ISSUE TITLE
Endpoint to auto-endorse an instance

### ISSUE THREAD

**Issue by db0** [XtremeOwnageDotCom/FediseerGui#17]
Since the GUI keeps a login cookie, we can use it to allow sites to set it up as an "endorse me" button. When clicked it would take you to an endpoint like `https://fediseer.lemmyonline.com/endorse/{domain}` and initiate the endorsement after a confirm dialogue (to avoid tricking people).

**Comment by XtremeOwnageDotCom** [comment]
I like this idea-

Should be able to knock it out tonight.

**Comment by XtremeOwnageDotCom** [comment]
Added new page,

`https://fediseer.lemmyonline.com/instances/endorse/{domain}`

aka,

`https://fediseer.lemmyonline.com/instances/endorse/lemmyonline.com`

Will be pushed shortly.
