### ISSUE TITLE
Failed Claim

### ISSUE THREAD

**Issue by shiribailem** [XtremeOwnageDotCom/FediseerGui#19]
I tried to claim my instance (foggyminds.com, platform: Friendica) and as I understand it I'm supposed to get an API key messaged to me, but that didn't happen.

Now it seems I'm not able to claim it because I never got the key and the key is needed to reset the key.

**Comment by XtremeOwnageDotCom** [comment]
@tmajibon I let db0 know about the issue in chat, and created a issue for you over on the fediseer page. 

On the GUI side, there isn't anything I can do to assist on this one. 

See https://github.com/db0/fediseer/issues/18
